/********************************************************************
 * Autogenerated file, do not edit.
 *******************************************************************/

#ifndef __GATT_DB_H
#define __GATT_DB_H

#include "sli_bt_gattdb_def.h"

extern const sli_bt_gattdb_t gattdb;

#define gattdb_generic_attribute              1
#define gattdb_service_changed_char           3
#define gattdb_database_hash                  6
#define gattdb_client_support_features        8
#define gattdb_device_name                    11
#define gattdb_device_information             14
#define gattdb_manufacturer_name_string       16
#define gattdb_model_number_string            18
#define gattdb_hardware_revision_string       20
#define gattdb_firmware_revision_string       22
#define gattdb_system_id                      24
#define gattdb_env_sensing                    25
#define gattdb_temperature                    27
#define gattdb_measurement_interval           30
#define gattdb_humidity_0                     32
#define gattdb_irradiance_0                   35
#define gattdb_automation_io                  37
#define gattdb_digital                        39
#define gattdb_ota                            40
#define gattdb_ota_control                    42


#endif // __GATT_DB_H
